from mongoeco.core.aggregation.accumulators import (
    _ACCUMULATOR_FLAGS_KEY,
    _accumulator_flags,
    _apply_accumulators,
    _finalize_accumulators,
    _initialize_accumulators,
)
from mongoeco.core.aggregation.runtime import (
    AggregationStageContext,
    _CURRENT_COLLECTION_RESOLVER_KEY,
    _MISSING,
    _aggregation_key,
    _bson_document_size,
    _expression_truthy,
    _resolve_aggregation_field_path,
    evaluate_expression,
)
from mongoeco.core.aggregation.planning import (
    AggregationPushdown,
    Pipeline,
    PipelineStage,
    _is_simple_projection,
    _match_spec_contains_expr,
    _require_projection,
    split_pushdown_pipeline,
)
from mongoeco.core.aggregation.extensions import (
    AggregationExpressionExtensionContext,
    AggregationExpressionExtensionHandler,
    AggregationStageExecutionMode,
    AggregationStageExtensionHandler,
    get_registered_aggregation_expression_operator,
    get_registered_aggregation_stage,
    register_aggregation_expression_operator,
    register_aggregation_stage,
    registered_aggregation_expression_operator,
    registered_aggregation_stage,
    unregister_aggregation_expression_operator,
    unregister_aggregation_stage,
)
from mongoeco.core.aggregation.spill import (
    BLOCKING_AGGREGATION_STAGES,
    AggregationSpillPolicy,
)
from mongoeco.core.aggregation.cost import AggregationCostPolicy
from mongoeco.core.aggregation.grouping_stages import _apply_group
from mongoeco.core.aggregation.stages import (
    AGGREGATION_STAGE_HANDLERS,
    AGGREGATION_STAGE_SPECS,
    AggregationStageHandler,
    AggregationStageSpec,
    apply_pipeline,
    get_aggregation_stage_spec,
    has_materializing_aggregation_stage,
    is_streamable_aggregation_stage,
)

__all__ = [
    "AGGREGATION_STAGE_HANDLERS",
    "AGGREGATION_STAGE_SPECS",
    "AggregationPushdown",
    "AggregationExpressionExtensionContext",
    "AggregationExpressionExtensionHandler",
    "AggregationStageExecutionMode",
    "AggregationStageContext",
    "AggregationStageExtensionHandler",
    "AggregationStageHandler",
    "AggregationStageSpec",
    "AggregationSpillPolicy",
    "AggregationCostPolicy",
    "BLOCKING_AGGREGATION_STAGES",
    "Pipeline",
    "PipelineStage",
    "_ACCUMULATOR_FLAGS_KEY",
    "_CURRENT_COLLECTION_RESOLVER_KEY",
    "_MISSING",
    "_accumulator_flags",
    "_aggregation_key",
    "_apply_accumulators",
    "_apply_group",
    "_bson_document_size",
    "_expression_truthy",
    "_finalize_accumulators",
    "_initialize_accumulators",
    "_is_simple_projection",
    "_match_spec_contains_expr",
    "_require_projection",
    "_resolve_aggregation_field_path",
    "apply_pipeline",
    "evaluate_expression",
    "get_aggregation_stage_spec",
    "has_materializing_aggregation_stage",
    "get_registered_aggregation_expression_operator",
    "get_registered_aggregation_stage",
    "is_streamable_aggregation_stage",
    "register_aggregation_expression_operator",
    "register_aggregation_stage",
    "registered_aggregation_expression_operator",
    "registered_aggregation_stage",
    "split_pushdown_pipeline",
    "unregister_aggregation_expression_operator",
    "unregister_aggregation_stage",
]
