from mongoeco.core.aggregation.runtime import (
    AggregationStageContext,
    _ACCUMULATOR_FLAGS_KEY,
    _CURRENT_COLLECTION_RESOLVER_KEY,
    _MISSING,
    _accumulator_flags,
    _aggregation_key,
    _apply_accumulators,
    _bson_document_size,
    _expression_truthy,
    _finalize_accumulators,
    _initialize_accumulators,
    _resolve_aggregation_field_path,
    evaluate_expression,
)
from mongoeco.core.aggregation.planning import (
    AggregationPushdown,
    Pipeline,
    PipelineStage,
    _is_simple_projection,
    _match_spec_contains_expr,
    _require_projection,
    split_pushdown_pipeline,
)
from mongoeco.core.aggregation.grouping_stages import _apply_group
from mongoeco.core.aggregation.stages import (
    AGGREGATION_STAGE_HANDLERS,
    AggregationStageHandler,
    apply_pipeline,
)

__all__ = [
    "AGGREGATION_STAGE_HANDLERS",
    "AggregationPushdown",
    "AggregationStageContext",
    "AggregationStageHandler",
    "Pipeline",
    "PipelineStage",
    "_ACCUMULATOR_FLAGS_KEY",
    "_CURRENT_COLLECTION_RESOLVER_KEY",
    "_MISSING",
    "_accumulator_flags",
    "_aggregation_key",
    "_apply_accumulators",
    "_apply_group",
    "_bson_document_size",
    "_expression_truthy",
    "_finalize_accumulators",
    "_initialize_accumulators",
    "_is_simple_projection",
    "_match_spec_contains_expr",
    "_require_projection",
    "_resolve_aggregation_field_path",
    "apply_pipeline",
    "evaluate_expression",
    "split_pushdown_pipeline",
]
