from mongoeco.compat.base import (
    MongoDialect,
    MONGODB_DIALECT_HOOK_NAMES,
    MONGODB_DIALECT_70,
    MONGODB_DIALECT_80,
    MONGODB_DIALECT_ALIASES,
    MONGODB_DIALECT_BEHAVIOR_FLAGS,
    MONGODB_DIALECT_CAPABILITIES,
    MONGODB_DIALECT_POLICY_SPECS,
    MONGODB_DIALECTS,
    MongoDialect70,
    MongoDialect80,
    PYMONGO_PROFILE_HOOK_NAMES,
    PYMONGO_PROFILE_49,
    PYMONGO_PROFILE_411,
    PYMONGO_PROFILE_413,
    PYMONGO_PROFILE_ALIASES,
    PYMONGO_PROFILE_BEHAVIOR_FLAGS,
    PYMONGO_PROFILE_CAPABILITIES,
    PYMONGO_PROFILES,
    PyMongoProfile,
    PyMongoProfile49,
    PyMongoProfile411,
    PyMongoProfile413,
    SUPPORTED_MONGODB_MAJORS,
    SUPPORTED_PYMONGO_MAJORS,
)
from mongoeco.compat.catalog import (
    DATABASE_COMMAND_SUPPORT_CATALOG,
    DATABASE_COMMAND_OPTION_SUPPORT_CATALOG,
    export_cxp_catalog,
    export_cxp_operation_catalog,
    export_cxp_profile_catalog,
    export_cxp_profile_support_catalog,
    export_full_compat_catalog,
    export_full_compat_catalog_markdown,
    export_database_command_catalog,
    export_database_command_option_catalog,
    export_mongodb_dialect_catalog,
    MONGODB_CAP_NULL_QUERY_MATCHES_UNDEFINED,
    MongoBehaviorPolicySpec,
    export_local_runtime_subset_catalog,
    export_operation_option_catalog,
    PYMONGO_CAP_UPDATE_ONE_SORT,
    export_pymongo_profile_catalog,
)
from mongoeco.compat.operation_support import (
    get_operation_option_support,
    is_operation_option_effective,
    OPERATION_OPTION_SUPPORT,
    OperationOptionSupport,
    OptionSupportStatus,
    UNSUPPORTED_OPERATION_OPTION,
)
from mongoeco.compat.registry import (
    AUTO_INSTALLED_PYMONGO_PROFILE,
    DEFAULT_MONGODB_DIALECT,
    DEFAULT_PYMONGO_PROFILE,
    detect_installed_pymongo_profile,
    detect_installed_pymongo_profile_resolution,
    MongoDialectResolution,
    PyMongoProfileResolution,
    resolve_mongodb_dialect_resolution,
    resolve_mongodb_dialect,
    resolve_pymongo_profile,
    resolve_pymongo_profile_resolution,
    STRICT_AUTO_INSTALLED_PYMONGO_PROFILE,
)

_DIALECT_EXPORTS = (
    'MongoDialect',
    'MONGODB_DIALECT_HOOK_NAMES',
    'MONGODB_DIALECT_70',
    'MONGODB_DIALECT_80',
    'MONGODB_DIALECTS',
    'MONGODB_DIALECT_ALIASES',
    'MONGODB_DIALECT_CAPABILITIES',
    'MONGODB_DIALECT_BEHAVIOR_FLAGS',
    'MONGODB_DIALECT_POLICY_SPECS',
    'MongoDialect70',
    'MongoDialect80',
    'MongoBehaviorPolicySpec',
    'SUPPORTED_MONGODB_MAJORS',
    'DEFAULT_MONGODB_DIALECT',
    'MongoDialectResolution',
    'resolve_mongodb_dialect',
    'resolve_mongodb_dialect_resolution',
)

_PROFILE_EXPORTS = (
    'PyMongoProfile',
    'PYMONGO_PROFILE_HOOK_NAMES',
    'PYMONGO_PROFILE_49',
    'PYMONGO_PROFILE_411',
    'PYMONGO_PROFILE_413',
    'PYMONGO_PROFILES',
    'PYMONGO_PROFILE_ALIASES',
    'PYMONGO_PROFILE_CAPABILITIES',
    'PYMONGO_PROFILE_BEHAVIOR_FLAGS',
    'PyMongoProfile49',
    'PyMongoProfile411',
    'PyMongoProfile413',
    'SUPPORTED_PYMONGO_MAJORS',
    'DEFAULT_PYMONGO_PROFILE',
    'AUTO_INSTALLED_PYMONGO_PROFILE',
    'STRICT_AUTO_INSTALLED_PYMONGO_PROFILE',
    'PyMongoProfileResolution',
    'resolve_pymongo_profile',
    'resolve_pymongo_profile_resolution',
    'detect_installed_pymongo_profile',
    'detect_installed_pymongo_profile_resolution',
)

_OPTION_EXPORTS = (
    'OptionSupportStatus',
    'OperationOptionSupport',
    'OPERATION_OPTION_SUPPORT',
    'UNSUPPORTED_OPERATION_OPTION',
    'get_operation_option_support',
    'is_operation_option_effective',
    'export_operation_option_catalog',
)

_CATALOG_EXPORTS = (
    'export_mongodb_dialect_catalog',
    'export_pymongo_profile_catalog',
    'export_database_command_catalog',
    'export_database_command_option_catalog',
    'export_cxp_catalog',
    'export_cxp_operation_catalog',
    'export_cxp_profile_catalog',
    'export_cxp_profile_support_catalog',
    'export_full_compat_catalog',
    'export_full_compat_catalog_markdown',
)

__all__ = [
    *_DIALECT_EXPORTS,
    *_PROFILE_EXPORTS,
    *_OPTION_EXPORTS,
    *_CATALOG_EXPORTS,
]
