from pathlib import Path


__path__ = [str(Path(__file__).resolve().parent.parent / "src" / "mongoeco")]

from .api import AsyncMongoClient, MongoClient
from ._version import __version__
from .errors import CollectionInvalid
from .compat import (
    AUTO_INSTALLED_PYMONGO_PROFILE,
    DEFAULT_MONGODB_DIALECT,
    DEFAULT_PYMONGO_PROFILE,
    detect_installed_pymongo_profile,
    detect_installed_pymongo_profile_resolution,
    MONGODB_DIALECT_HOOK_NAMES,
    MONGODB_DIALECT_70,
    MONGODB_DIALECT_80,
    MONGODB_DIALECT_ALIASES,
    MONGODB_DIALECT_BEHAVIOR_FLAGS,
    MONGODB_DIALECT_CAPABILITIES,
    MONGODB_DIALECTS,
    MongoDialect,
    MongoDialectResolution,
    MongoDialect70,
    MongoDialect80,
    PYMONGO_PROFILE_49,
    PYMONGO_PROFILE_411,
    PYMONGO_PROFILE_413,
    PYMONGO_PROFILE_HOOK_NAMES,
    PYMONGO_PROFILE_ALIASES,
    PYMONGO_PROFILE_BEHAVIOR_FLAGS,
    PYMONGO_PROFILE_CAPABILITIES,
    PYMONGO_PROFILES,
    PyMongoProfile,
    PyMongoProfile49,
    PyMongoProfile411,
    PyMongoProfile413,
    PyMongoProfileResolution,
    get_operation_option_support,
    is_operation_option_effective,
    OPERATION_OPTION_SUPPORT,
    OperationOptionSupport,
    OptionSupportStatus,
    export_full_compat_catalog,
    export_mongodb_dialect_catalog,
    export_operation_option_catalog,
    export_pymongo_profile_catalog,
    UNSUPPORTED_OPERATION_OPTION,
    resolve_mongodb_dialect_resolution,
    resolve_mongodb_dialect,
    resolve_pymongo_profile,
    resolve_pymongo_profile_resolution,
    STRICT_AUTO_INSTALLED_PYMONGO_PROFILE,
    SUPPORTED_MONGODB_MAJORS,
    SUPPORTED_PYMONGO_MAJORS,
)
from .session import ClientSession
from .types import (
    Binary, BulkWriteResult, CodecOptions, DBRef, Decimal128, DeleteMany, DeleteOne, IndexDefinition,
    IndexModel, InsertOne, ObjectId, ReadConcern, ReadPreference, ReadPreferenceMode, Regex, ReplaceOne,
    ReturnDocument, SearchIndexDefinition, SearchIndexModel, SON, Timestamp, TransactionOptions, UNDEFINED,
    UndefinedType, UpdateMany, UpdateOne, WriteConcern,
)

__all__ = [
    "AsyncMongoClient",
    "MongoClient",
    "DEFAULT_MONGODB_DIALECT",
    "DEFAULT_PYMONGO_PROFILE",
    "AUTO_INSTALLED_PYMONGO_PROFILE",
    "STRICT_AUTO_INSTALLED_PYMONGO_PROFILE",
    "MongoDialect",
    "MongoDialectResolution",
    "MONGODB_DIALECT_HOOK_NAMES",
    "MONGODB_DIALECT_70",
    "MONGODB_DIALECT_80",
    "MONGODB_DIALECTS",
    "MONGODB_DIALECT_ALIASES",
    "MONGODB_DIALECT_CAPABILITIES",
    "MONGODB_DIALECT_BEHAVIOR_FLAGS",
    "MongoDialect70",
    "MongoDialect80",
    "PyMongoProfile",
    "PYMONGO_PROFILE_HOOK_NAMES",
    "PYMONGO_PROFILE_49",
    "PYMONGO_PROFILE_411",
    "PYMONGO_PROFILE_413",
    "PYMONGO_PROFILES",
    "PYMONGO_PROFILE_ALIASES",
    "PYMONGO_PROFILE_CAPABILITIES",
    "PYMONGO_PROFILE_BEHAVIOR_FLAGS",
    "PyMongoProfile49",
    "PyMongoProfile411",
    "PyMongoProfile413",
    "PyMongoProfileResolution",
    "OptionSupportStatus",
    "OperationOptionSupport",
    "OPERATION_OPTION_SUPPORT",
    "export_mongodb_dialect_catalog",
    "export_pymongo_profile_catalog",
    "export_operation_option_catalog",
    "export_full_compat_catalog",
    "UNSUPPORTED_OPERATION_OPTION",
    "get_operation_option_support",
    "is_operation_option_effective",
    "SUPPORTED_MONGODB_MAJORS",
    "SUPPORTED_PYMONGO_MAJORS",
    "resolve_mongodb_dialect_resolution",
    "resolve_mongodb_dialect",
    "resolve_pymongo_profile",
    "resolve_pymongo_profile_resolution",
    "detect_installed_pymongo_profile",
    "detect_installed_pymongo_profile_resolution",
    "ClientSession",
    "CollectionInvalid",
    "InsertOne",
    "UpdateOne",
    "UpdateMany",
    "ReplaceOne",
    "DeleteOne",
    "DeleteMany",
    "IndexDefinition",
    "IndexModel",
    "SearchIndexDefinition",
    "SearchIndexModel",
    "BulkWriteResult",
    "WriteConcern",
    "ReadConcern",
    "ReadPreference",
    "ReadPreferenceMode",
    "CodecOptions",
    "TransactionOptions",
    "Binary",
    "Regex",
    "Timestamp",
    "Decimal128",
    "SON",
    "DBRef",
    "ObjectId",
    "ReturnDocument",
    "UndefinedType",
    "UNDEFINED",
    "__version__",
]
