from pathlib import Path
import json,hashlib,shutil,subprocess,datetime,re
root=Path('/Users/uve/Proyectos/mongoeco');base=Path('/private/tmp/mongoeco-490-20261008');target=root/'docs/evidence/mongoeco-4.9.0'
def read(name):return json.loads((base/name).read_text())
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()
coverage=read('coverage-final314.json')['totals'];assert coverage['percent_covered']>=99
for name in ['consumer-corrected-status.json','contract-gate-status.json']:assert all(v==0 for v in read(name).values())
for python in ['313','314']:assert '8803 passed, 30 skipped, 3990 subtests passed' in (base/f'pytest-final{python}.log').read_text()
assert not any('ResourceWarning' in (base/f'pytest-final{p}.log').read_text() for p in ['313','314'])
for name in ['performance-baseline-streaming.json','performance-candidate-streaming.json','performance-baseline-spill.json','performance-candidate-spill.json','clean-delivery-sdist-identity.json','native-cleanup-final.json']:assert (base/name).exists()
assert read('performance-final-summary.json')['all_contracts_pass']
assert read('performance-causal-reuse.json')['only_changed_package_files']==['mongoeco/driver/execution.py']
assert all(v==0 for v in read('callback-close-status.json').values())
assert read('performance-supplemental-causal-reuse.json')['changed_execution_pipeline_calls']==0
assert read('profile-matrix-summary.json')==json.loads((root/'tests/fixtures/pymongo_profile_matrix.json').read_text())
for v,checks in read('profile-matrix-full.json').items():assert all(isinstance(d['accepted'],bool) for d in checks.values())
initial=read('initial-workset.json');missing=[p for p in initial['files'] if not (root/p).is_file()];assert not missing,missing
unchanged_fixtures={p:h for p,h in initial['files'].items() if p.startswith('tests/fixtures/') and p not in ['tests/fixtures/public_api_manifest_exchange_source.json','tests/fixtures/pymongo_profile_matrix.json']}
for p,h in unchanged_fixtures.items():assert digest(root/p)==h,p
assert digest(root/'scripts/ruff_ratchet_baseline.json')==initial['files']['scripts/ruff_ratchet_baseline.json']
artifacts=root/'dist/4.9.0-candidate';artifacts.mkdir(parents=True,exist_ok=True)
for p in (base/'dist-callback-first').iterdir():
 if p.suffix in ['.whl','.gz']:shutil.copy2(p,artifacts/p.name)
hashes={p.name:digest(p) for p in artifacts.iterdir() if p.is_file() and p.suffix in ['.whl','.gz']}
assert hashes==read('evidence/distribution-callback-hashes.json')
(artifacts/'SHA256SUMS').write_text(''.join(f'{sha}  {name}\n' for name,sha in hashes.items()))
matrix_path=target/'capture-coverage.json';matrix=json.loads(matrix_path.read_text());assert len(matrix['rows'])==852
matrix['state']='final native recapture and installed-wheel validation complete; captured-only rows excluded from parity';matrix_path.write_text(json.dumps(matrix,indent=2,ensure_ascii=False)+'\n')
# Archive actual results and the unchanged measurement/verification harnesses.
names=['initial-workset.json','initial.diff','impact-census.md','consumer-census.json','transitive-owner-census.json','consumer-adoption-final.json','consumer-sdk-pin-adaptation.json','consumer-preexisting-test-adaptation.json','consumer-corrected-status.json','consumer-corrected-summary.log','consumer-final-pip-check.log','consumer-sdk418-install.log','consumer-testkit-baseline-git-scaffold.log','consumer-testkit-final-git-scaffold.log','consumer-testkit-baseline-adapted.log','consumer-testkit-final-adapted.log','consumer-testkit-baseline-injected-sqlite.log','consumer-testkit-final-sdk418-explicit-sqlite.log','consumer-typing.log','corrected-consumer-identity.json','corrected-wheel313-identity.json','corrected-wheel314-identity.json','distribution-current-source-identity.json','contract-gate-status.json','coverage-final314.json','pytest-final313.log','pytest-final314.log','unittest-final.log','typing-final-source.log','manifest-final-source.log','typing-wheel-final.log','manifest-wheel-final.log','exports-wheel-final.log','external-consumer-final.log','property-ci-final.log','property-deep-final.log','lint-callback-final.log','sqlite45-final.log','sqlite45-original-integrity.json','native-final-verification.json','native-cleanup-final.json','profile-matrix-full.json','profile-matrix-summary.json','profile-matrix-final.log','ci-config-validation.json','ci-config-final.log','clean-wheel-smoke.log','clean-wheel-final-pip-check.log','clean-wheel-final-identity.json','clean-delivery-sdist-install.log','clean-delivery-sdist-pip-check.log','clean-delivery-sdist-smoke.log','clean-delivery-sdist-smoke.json','clean-delivery-sdist-identity.json','minimal313-result.json','minimal313-result.log','minimal313-install.log','build-callback-artifacts.log','benchmark-baseline-final-identity.json','baseline-pypi-metadata.json','benchmark-baseline-memory.json','benchmark-baseline-memory.md','benchmark-baseline-sqlite.json','benchmark-baseline-sqlite-report.json','benchmark-baseline-sqlite-report.md','benchmark-corrected-memory.json','benchmark-corrected-memory.md','benchmark-corrected-memory.log','benchmark-corrected-sqlite.json','benchmark-corrected-sqlite.md','benchmark-corrected-sqlite.log','performance-final-summary.json','performance-main-comparison.json','semantic-work-baseline.json','semantic-work-corrected7.json','semantic-work-corrected9.json','performance-supplement-summary.log','streaming-recheck-summary.log','streaming-profile-diagnostic.json','streaming-baseline-profile.log','streaming-candidate-profile.log','measure_semantic_work.py','measure_streamed_aggregation.py','observe_spill.py','compose_benchmark_report.py','verify_installed_identity.py','verify_minimal.py','build_delivery_candidate.py','recheck_streaming.py','profile_streaming.py','close_evidence.py']
names += ['build_callback_candidate.py','performance-supplemental-causal-reuse.json','performance-supplemental-causal-reuse.log','verify_supplemental_causal_reuse.py','performance-causal-reuse.json','performance-causal-reuse.log','timed-wheel314-identity.json','callback-close-status.json','callback-close-summary.log','public-callback-regression-final.log','public-callback-authorized-focused.log','delivery-inventory-authorized-final.log','verify_performance_causal_reuse.py','verify_native_final.py','clean-callback-install-summary.log','clean-callback-wheel-install.log','clean-callback-sdist-install.log','clean-callback-wheel-smoke.json','clean-callback-sdist-smoke.json','clean-callback-wheel-identity.json','clean-callback-sdist-identity.json','consumer-callback-summary.log','native-callback-recapture-summary.log']
names += [p.name for p in base.glob('consumer-corrected-*.log')]
names += [p.name for p in base.glob('native*-final.*')]
names += [p.name for p in base.glob('conformance-*-final.*')]
names += [p.name for p in base.glob('performance-*-streaming.*')]+[p.name for p in base.glob('performance-*-spill.*')]
names += [p.name for p in base.glob('streaming-recheck-*-*.json')]
for name in sorted(set(names)):
 p=base/name;assert p.is_file(),p;shutil.copy2(p,target/p.name)
for name in ['distribution-callback-hashes.json','build-callback-first.log','build-callback-second.log']:shutil.copy2(base/'evidence'/name,target/name)
shutil.copy2(base/'consumer-run/consumer_explicit_profiles.py',target/'consumer_explicit_profiles.py')
shutil.copy2(base/'loop-finalizer-diagnostics.jsonl',target/'loop-finalizer-diagnostics.jsonl')
shutil.copy2(base/'source-final-pytest.log',target/'diagnostic-source-before-corrected-wheel.log')
gates=[
 {'gate':'pytest Python 3.13 / 3.14 installed wheel','result':'8803 passed / 30 expected skips / 3990 subtests each','evidence':['pytest-final313.log','pytest-final314.log','corrected-wheel313-identity.json','corrected-wheel314-identity.json']},
 {'gate':'coverage >=99 without new exclusions','result':coverage,'evidence':['coverage-final314.json']},
 {'gate':'unittest','result':'3596 tests; 2 expected skips; OK','evidence':['unittest-final.log']},
 {'gate':'properties ci / deep','result':'9 passed each; shrinking enabled','evidence':['property-ci-final.log','property-deep-final.log']},
 {'gate':'lint ratchet last release','result':'78 changed Python files; unchanged baseline; v4.8.1','evidence':['lint-callback-final.log']},
 {'gate':'typing / manifest / exports source and installed wheel','result':'positive and negative contract canaries pass; current and historical snapshots active','evidence':['typing-final-source.log','manifest-final-source.log','typing-wheel-final.log','manifest-wheel-final.log','exports-wheel-final.log']},
 {'gate':'conformance Memory / SQLite / external SPI canary','result':'10/10; 10/10; 5 passed plus 5 not applicable; no failures/errors','evidence':['conformance-memory-final.json','conformance-sqlite-final.json','conformance-external-final.json']},
 {'gate':'isolated installed owner consumers','result':'provider default/explicit 21 each (130 managed-server cases deselected); testkit 135 each; gdt 39; typing canary passes; full resolution pip check','evidence':['consumer-corrected-status.json','consumer-adoption-final.json','consumer-final-pip-check.log','corrected-consumer-identity.json']},
 {'gate':'strict native 7 / 8 / 9 and four corpora','result':'29 live parity cases per version; 284 fresh capture comparisons per version; zero unexpected omissions; stable exact FCV','evidence':['native-final-verification.json','native-cleanup-final.json','capture-coverage.json']},
 {'gate':'five isolated PyMongo versions','result':'exact curated summary; no indeterminate results','evidence':['profile-matrix-full.json','profile-matrix-summary.json']},
 {'gate':'SQLite 4.5 original preservation','result':'6 tests pass using copies; original hash unchanged','evidence':['sqlite45-final.log','sqlite45-original-integrity.json']},
 {'gate':'minimum dependencies / clean wheel and final sdist','result':'full public resolution without internal constraints; optional modules absent in minimal lane; final sdist package bytes match wheel','evidence':['minimal313-result.json','clean-wheel-final-identity.json','clean-delivery-sdist-identity.json','clean-delivery-sdist-smoke.json','clean-callback-wheel-install.log','clean-callback-sdist-install.log']},
 {'gate':'two reproducible builds and twine','result':hashes,'evidence':['build-callback-artifacts.log','distribution-callback-hashes.json','distribution-current-source-identity.json']},
 {'gate':'performance / outcome / plans / deterministic work','result':'14 main tasks strict comparison; additional streaming three rounds of 5 reps each; spill actually observed and cleaned; all samples and limitations retained','evidence':['performance-final-summary.json','performance-causal-reuse.json','timed-wheel314-identity.json','benchmark-corrected-memory.json','benchmark-corrected-sqlite.json']},
 {'gate':'CI / documentation / final diff review','result':'3 YAML / 75 shell / 4 embedded Python parse; local gates only; no hosted CI run; final source diff reviewed','evidence':['ci-config-validation.json']}
]
receipt={'schema':'mongoeco-candidate-validation/1','version':'4.9.0','state':'prepared and locally verified; not committed, tagged or published','generated_at':datetime.datetime.now(datetime.UTC).isoformat(),'base':initial['base'],'last_release':initial['last_release'],'initial_workset_manifest_sha256':digest(base/'initial-workset.json'),'initial_workset_files_preserved':len(initial['files']),'historical_fixture_hashes_unchanged':len(unchanged_fixtures),'artifacts':{name:{'path':str(artifacts/name),'sha256':sha} for name,sha in hashes.items()},'gates':gates,'guarantees_preserved':['defaults MongoDB 7.0 / PyMongo 4.9','separate server dialect / Python profile / wire capabilities','Engine SPI v2 / search-v1 / CXP exchange / persistent formats','sync-async and promised Memory-SQLite paths','lexical bindings, namespace, placement, resources, deadlines, cleanup and validation precedence','direct convert and group guards, SRV, versioned merge order, independent public flags','public preparation callbacks retain the historical call shape and resource ownership'],'observable_corrections':['densify 7/8 now preserves original documents and multiplicity, half-open explicit bounds, empty ranges and native version deltas','date window comparisons accept valid internal limits outside Python datetime range','empty/malformed variable names and paths have native error classification and precedence','builtin id recreation returns requested names with immutable storage identity; conflicting index definitions code 86'],'limits':['431 of 852 matrix rows remain captured-only; full BSON wrapper identity and all mapping-order semantics are not claimed by normalized value comparisons','full native index metadata and explicit unique semantics are outside declared parity; deliberate product extensions preserved','owner adoption not applied: pins, SDK constraint, explicit configuration wiring and preexisting CXP test adaptation remain owner work','performance does not establish global non-regression, causal speedup or memory bounds; positive and negative timing deltas retained','CI hosted execution and publication are outside this local preparation'],'pending_required_work':[],'publication_performed':False,'owner_repositories_modified':False}
# This manifest covers all authored tracked/nonignored input files, excluding this
# new evidence directory to avoid self-reference; evidence has a separate inventory.
files=subprocess.check_output(['git','ls-files','--cached','--others','--exclude-standard','-z'],cwd=root).decode().split('\0')
manifest={p:digest(root/p) for p in sorted(set(files)) if p and (root/p).is_file() and not p.startswith('docs/evidence/mongoeco-4.9.0/')}
workset={'base':initial['base'],'scope':'all tracked/nonignored files except docs/evidence/mongoeco-4.9.0; evidence inventoried separately; ignored artifacts identified explicitly','files':manifest}
(target/'final-workset.json').write_text(json.dumps(workset,indent=2)+'\n');receipt['final_workset_manifest_sha256']=digest(target/'final-workset.json')
receipt['evidence_files']={p.name:digest(p) for p in sorted(target.iterdir()) if p.is_file() and p.name!='validation.json'}
(target/'validation.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False)+'\n')
print('Prepared:',len(receipt['gates']),'gates;',len(receipt['evidence_files']),'evidence files;',hashes)
