from typing import AsyncIterable, Protocol, runtime_checkable

from mongoeco.session import ClientSession
from mongoeco.types import DeleteResult, Document, DocumentId, Filter, Projection, SortSpec, Update, UpdateResult


@runtime_checkable
class AsyncStorageEngine(Protocol):
    """Protocolo Delgado (Thin Protocol) de Almacenamiento."""

    def create_session_state(self, session: ClientSession) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def put_document(self, db_name: str, coll_name: str, document: Document, overwrite: bool = True, *, context: ClientSession | None = None) -> bool: ...
    async def get_document(self, db_name: str, coll_name: str, doc_id: DocumentId, *, projection: Projection | None = None, context: ClientSession | None = None) -> Document | None: ...
    async def delete_document(self, db_name: str, coll_name: str, doc_id: DocumentId, *, context: ClientSession | None = None) -> bool: ...
    def scan_collection(self, db_name: str, coll_name: str, filter_spec: Filter | None = None, *, projection: Projection | None = None, sort: SortSpec | None = None, skip: int = 0, limit: int | None = None, context: ClientSession | None = None) -> AsyncIterable[Document]: ...
    async def update_matching_document(self, db_name: str, coll_name: str, filter_spec: Filter, update_spec: Update, upsert: bool = False, upsert_seed: Document | None = None, *, context: ClientSession | None = None) -> UpdateResult[DocumentId]: ...
    async def delete_matching_document(self, db_name: str, coll_name: str, filter_spec: Filter, *, context: ClientSession | None = None) -> DeleteResult: ...
    async def count_matching_documents(self, db_name: str, coll_name: str, filter_spec: Filter, *, context: ClientSession | None = None) -> int: ...
    async def create_index(self, db_name: str, coll_name: str, fields: list[str], *, unique: bool = False, name: str | None = None, context: ClientSession | None = None) -> str: ...
    async def list_indexes(self, db_name: str, coll_name: str, *, context: ClientSession | None = None) -> list[dict[str, object]]: ...
    async def list_databases(self) -> list[str]: ...
    async def list_collections(self, db_name: str) -> list[str]: ...
    async def drop_collection(self, db_name: str, coll_name: str) -> None: ...
